### ISSUE TITLE
Support for `condition`

### ISSUE THREAD

**Issue by sunkan** [ktomk/pipelines#13]
Hi

What I can see the library don't support [condition and changesets](https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/#condition)

I saw that you have a test yaml file with the structure [test/data/yml/condition.yml](https://github.com/ktomk/pipelines/blob/master/test/data/yml/condition.yml) but it don't seem to be used for anything else than to verify that its a valid pipeline config

So is this something that would be possible to implement or would you be open to a pull-request?

---
Yes we use git. And we only use it in BitBucket

How the detection work in BitBucket:

- In the `branches` sections they looks in the last commit and sees if any files matches the `includePaths` and if so run the step. This should be fairly simple to implement
- In the `pull-requests` section it will look in all commits for changes that matches `includePaths`. This might be harder but maybe we could require an option with a destionation branch and do the check against that diff?

Usage example:

```yaml

pipelines:
  pull-requests:
      '**': #this runs as default for any branch not elsewhere defined
          - step:
                script:
                    - phpunit
                condition:
                    changesets:
                        includePaths:
                            - src/
                            - composer.lock

          - step:
                script:
                    - eslint
                condition:
                    changesets:
                        includePaths:
                            - js/

    branches:
        master:
            - step:
                  script:
                      - phpunit
                  condition:
                      changesets:
                          includePaths:
                              - src/
                              - composer.lock
```
