### ISSUE TITLE
/bin/sh: 5: source: not found

### ISSUE THREAD

**Issue by Timple** [ktomk/pipelines#17]
Our images in the bitbucket-pipelines have bash as default runner. Can this be adhered?

This does not only affect the `source` command, which we could easily replace by `.`. But also environment variables that should be present are not there.

**Comment by ktomk** [comment]
Good question. `/bin/sh` has the design decision as we expect every Docker container to have it. This is albeit we're aware that Atlassian Bitbucket Pipelines supports both `/bin/sh` and `/bin/bash` (and IIRC prefers `/bin/bash` if available).

A couple of questions for clarification:

* Can you share the path of `bash` in your scenario within the container?
* Is only the `script` and `after-script` execution affected by it? (Copying files, caches and artifacts work?)
* Can you provide an exemplary pipleines YAML w/ such a script to test with?

We can then figure something out how to better support the `bash` use-case I'm pretty sure.

The second issue with the environment variables that are not present is less clear to me, perhaps if an exemplary script could show this as well would be helpful to write more.

**Comment by Timple** [comment]
We're using ubuntu dockers as base images (but with bash as SHELL). 

- So path is `/bin/bash`
- Yes, no other issues

- This should do it:

```Dockerfile
FROM ubuntu:latest
SHELL ["/bin/bash", "-c"] 
```

`docker build -t ubuntu-bash .`

```yaml   
image: ubuntu-bash
pipelines:
  default:
    - step:
        name: Build and test
        script:
          - source /etc/os-release
          - echo "$PRETTY_NAME"
```

**Comment by ktomk** [comment]
Thanks. Is the `PRETTY_NAME` parameter non-null in the good case and null/undefined in the reported issue?

**Comment by Timple** [comment]
Yes, because the content of `/etc/os-release` is: 
```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
...
```

_(I put the wrong file to source in the example, copy past error. Fixed that now, so please modify in your trials as well)_

**Comment by ktomk** [comment]
Please find a temporary topic branch [`issue-17-bash` in action](https://github.com/ktomk/pipelines/actions?query=branch%3Aissue-17-bash). Build phar files (choose any) will be kept for two days so they can be used for early user testing.

I target release version 0.0.66 for the new bash runner feature.

**Comment by Timple** [comment]
Thank you for taking the time to fix this!
This did fix the example I posted. :slightly_smiling_face: 

Unfortunately it still doesn't work for our full system. So I've put together a new example :/

```Dockerfile
FROM ubuntu:latest
RUN echo "HELLO=YOU" > ~/.bashrc
SHELL ["/bin/bash", "-c"]
```

```yaml
image: ubuntu-bash
pipelines:
  default:
    - step:
        name: Build and test
        script:
          - echo "$HELLO"
          - source /etc/os-release
          - echo "$PRETTY_NAME"
```

Now the outcome is the same as from the docker command:
```bash
$ docker run ubuntu-bash echo "$HELLO"
<nothing>
```
```bash
$ ~/Downloads/pipelines.phar 
+++ step #1

    name...........: "Build and test"
    effective-image: ubuntu-bash
    container......: pipelines-1.Build-and-test.default.test
    container-id...: 7e400d87b793

+++ copying files into container...


+ echo "$HELLO"


+ source /etc/os-release

+ echo "$PRETTY_NAME"
Ubuntu 22.04 LTS
```

However, inside the docker:
```bash
$ docker run -it ubuntu-bash
root@10dc7d3e3e46:/# echo $HELLO
YOU
```

So from within the docker all variables declared in the .bashrc file are present. Looks like the pipelines run inside the dockerfile. This might be a completely different concept than what this project is doing?
