### ISSUE TITLE
BITBUCKET_REPO_SLUG holds the `.git` extension

### ISSUE THREAD

**Issue by Timple** [ktomk/pipelines#19]
In the bitbucket pipelines the BITBUCKET_REPO_SLUG does not hold the .git extension.

It's an inconsistency, but it's not documented anywhere by atlassian that is should not or cannot hold the .git extension.

**Comment by ktomk** [comment]
Can you give an example when `pipelines`  has `.git`  in `BITBUCKET_REPO_SLUG`?  Or please clarify what the report is about. @Timple

**Comment by Timple** [comment]
```yaml
image: ubuntu
pipelines:
  default:
    - step:
        script:
          - echo "$BITBUCKET_REPO_SLUG"
```

Typically a repository url looks like this:
https://bitbucket.org/company/somereponame

bitbucket pipelines:
BITBUCKET_REPO_SLUG=somereponame

pipelines.phar:
BITBUCKET_REPO_SLUG=somereponame.git
