### ISSUE TITLE
pipelines: file parse error: 'image' required in service definition

### ISSUE THREAD

**Issue by ortizman** [ktomk/pipelines#23]
The problem occurs when we define a custom service
Ex:

```
definitions:
   services:
     docker:
       memory: 5120
     docker-7g:
       type: docker
       memory: 7168
```
