### ISSUE TITLE
Parallel step support for fail-fast and steps properties

### ISSUE THREAD

**Issue by mashurex** [ktomk/pipelines#25]
When a `parallel` step is defined with the `fail-fast` and `steps` properties pipelines shows it as invalid.

Here is a sample that is perfectly valid and runs in BitBucket:
```
pipelines:
  custom:
    'custom-pipeline':
      - step: *stepA
      - parallel:
          fail-fast: true
          steps:
            - step: *stepB
            - step: *stepC
```

Pipelines does not allow the above and expects parallel steps to be defined only as an array, like this:

```
pipelines:
  custom:
    'custom-pipeline':
      - step: *stepA
      - parallel:
          - step: *stepB
          - step: *stepC
```
