### ISSUE TITLE
cannot parse yaml files with dash as indentation

### ISSUE THREAD

**Issue by mhewedy** [ktomk/pipelines#3]
Yaml spec 1.2 [says](https://yaml.org/spec/1.2/spec.html#id2777534):

> The  “-”, “?” and “:” characters used to denote block collection entries are perceived by people to be part of the indentation. This is handled on a case-by-case basis by the relevant productions.

However piplines fails when the file uses dash as identitation as follows:

```
pipelines:
  default:
  - step:
      name: Build and Test
```

it tells, theres no steps defined for default pipeline
