### ISSUE TITLE
git commands cannot be performed in pipeline

### ISSUE THREAD

**Issue by Timple** [ktomk/pipelines#30]
I have a pipeline which (indirectly) calls `git rev-parse --show-cdup`.

This works in bitbucket, but using pipelines.phar I get: 

```
fatal: not a git repository (or any of the parent directories): .git
```

Is there any effort being done here which removes the `.git` directory?

**Comment by ktomk** [comment]
No. If you use keep on failure and enter with a shell, does `/app/.git` exists? @Timple

**Comment by Timple** [comment]
Ah, there actually is.

Thanks for the tip on `--keep`. Running `git rev-parse --show-cdup` in the container gives:

```
root@b327e678ab84:/app# git rev-parse --show-cdup
fatal: detected dubious ownership in repository at '/app'
To add an exception for this directory, call:

	git config --global --add safe.directory /app
```

Seems like bitbucket does deem these repositories safe?

**Comment by ktomk** [comment]
Hmm, I know that error from git and this explains your original question as /app/.git is there it's just that `git(1)` does not consider it safe to without prior user interaction/configuration.

Interestingly I don't have it in my testing with pipelines, so a couple of questions to make a more educated guess on how this could become a zero-configuration when running a git pipeline (and also reproducing on my end):

Could you be so kind and provide the following details?

* Which user owns `/app` in your scenario and which user executes the container? 
* Are you making use of the `--user` flag?
* Do you run Docker rootless or do you use a docker replacement?
* What is the output of `git version --build-option` both on your box and inside the container
* Docker version could be useful, too.

My understanding is, it should be generally safe to add the `/app` deployment directory to the global (or system configuration) in a build container.

**Comment by Timple** [comment]
I'm not behind a linux machine at the moment.

But to reproduce this should be enough:

```yaml
definitions:
  caches:
    pre-commit: ~/.cache/pre-commit
  steps:
    - step: &nobleo-pre-commit
        name: Pre-commit
        image: salcatroppa/pre-commit
        caches: [pre-commit]
        script: [pre-commit run --all-files --verbose]

pipelines:
  default:
    - step: *nobleo-pre-commit
```

(perhaps you actually need the `.pre-commit-config.yaml` file):

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
```
