### ISSUE TITLE
Validator fails on pipes in steps

### ISSUE THREAD

**Issue by vincenzoromeo** [ktomk/pipelines#5]
### Background
I'm trying to validate my pipelines with `pipelines --show bitbucket-pipeline.yaml`.

Using latest `.phar` release as of time of writing.

_bitbucket-pipelines.yml_:
```yml
pipelines:

  branches:
    develop:
    - step:
        name: Deploy to staging
        deployment: staging
        script:
          - pipe: atlassian/rsync-deploy:0.4.2
            variables:
              USER: 'ec2-user'
              SERVER: '${SERVER_HOST}'
              REMOTE_PATH: '/home/ec2-user/app'
              LOCAL_PATH: '$PWD'
              EXTRA_ARGS: '--exclude=".git*"'
          - 'echo "Hello, World!"' 
```

### Expected Results
Expected this file to pass with flying colours - verified its correctness with the official online validator.

### Actual Results
```bash
pipelines --show bitbucket-pipelines.yml 
PIPELINE ID         IMAGES    STEPS                                                         
branches/develop    ERROR     'script' requires a list of commands, step #0 is not a command
```
