### ISSUE TITLE
Default pipeline with parallel fails validation

### ISSUE THREAD

**Issue by sunkan** [ktomk/pipelines#8]
Hi thanks for an awesome utility

I've a problem when defining a default pipeline with parallel step it just stops with 

```
$ pipelines --debug
pipelines: error: pipeline id 'default'
pipelines: file parse error: Missing required property 'step'
--------
class....: Ktomk\Pipelines\File\ParseException
message..: file parse error: Missing required property 'step'
code.....: 2
file.....: phar:///~/bin/pipelines/src/File/ParseException.php
line.....: 27
backtrace:
#0 phar:///~/bin/pipelines/src/File/Pipeline.php(106): Ktomk\Pipelines\File\ParseException::__()
#1 phar:///~/bin/pipelines/src/File/Pipeline.php(91): Ktomk\Pipelines\File\Pipeline->step()
#2 phar:///~/bin/pipelines/src/File/Pipeline.php(33): Ktomk\Pipelines\File\Pipeline->parseSteps()
#3 phar:///~/bin/pipelines/src/File/File.php(231): Ktomk\Pipelines\File\Pipeline->__construct()
#4 phar:///~/bin/pipelines/src/Utility/App.php(438): Ktomk\Pipelines\File\File->getById()
#5 phar:///~/bin/pipelines/src/Utility/App.php(141): Ktomk\Pipelines\Utility\App->getRunPipeline()
#6 phar:///~/bin/pipelines/src/Utility/ExceptionHandler.php(48): Ktomk\Pipelines\Utility\App->run()
#7 phar:///~/bin/pipelines/src/Utility/App.php(86): Ktomk\Pipelines\Utility\ExceptionHandler->handle()
#8 phar:///~/bin/pipelines/bin/pipelines(26): Ktomk\Pipelines\Utility\App->main()
#9 /~/bin/pipelines(14): require('phar:///~/...')
#10 {main}
--------

```

This is the smallest config I can reproduce the error with

**bitbucket-pipelines.yml**

```yml
image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        script:
          - echo "Step 1"
    - parallel:
        - step:
            script:
              - echo "Step 2.1"
        - step:
            script:
              - echo "Step 2.2"
```
